num_cs: 2
threads_per_cs: 2
num_ms: 1
mem_per_ms: 1073741824
base_rtt_ns: 300
initial_slabs_per_size: 32768
maintenance_cs: 1
threads_per_maintenance_cs: 1
log_level: INFO
ops_per_client: 100000
warmup_inserts: 100000
distribution:
  type: skewed
  key_space: 2000000
preset: write-only
cache:
  enabled: true
  max_size_kb: 65536
index: "faunus"
