num_cs: 2
threads_per_cs: 1
num_ms: 1
mem_per_ms: 134217728
base_rtt_ns: 0
initial_slabs_per_size: 32768
maintenance_cs: 0
threads_per_maintenance_cs: 0
# log_level: ERROR
log_level: DEBUG
ops_per_client: 10000
warmup_inserts: 0
# CPU core binding configuration
cpu_binding_enabled: false
cpu_binding_start_core: 0
cpu_isolation_required: false
distribution:
  type: uniform
  key_space: 2000000
operation_mix:
  insert: 1.0
  read: 0.0
  update: 0.0
  delete: 0.0
# ycsb_workload: a
cache:
  enabled: false
  max_size_kb: 16384
index: "sherman"
